### ISSUE TITLE
Empty data getting submitted

### ISSUE THREAD

**Issue by 777Prabhjot** [Satyasuranjeet/PicoAnime#44]
In the contact page data is getting submitted even if there is no value present in the inputs.

**Screen shot**
<img width="782" alt="Screenshot 2023-04-26 165232" src="https://user-images.githubusercontent.com/68184118/234560757-44863f9b-3fe8-4d99-8584-d00204e31291.png">

### **I would love to work on this**

**Comment by Satyasuranjeet** [comment]
It will be great if you fix that ☺️

**Comment by Satyasuranjeet** [comment]
fixed
